language: go

os:
- linux
- osx

before_deploy:
- ./tools/travis/bundle.sh

deploy:
  provider: releases
  api_key:
    secure: av6i5v9AAYHkUMpKH6wwxPHm9/SrUfEfaqZvzvfiNB3okRkZMslHGADjSfLXyF0gRKr70R78y0fpAlzpp1lmpnvS/LQ6nbXbIYlU9ByEj5LdjTb5AFjqxpXH5djMqYR2t7td5ZCO+SofRru60fKoAdDFSikDJjFErgrAb2JtS2z4uuMMHIypU6yiqXmUiOGnZq6pqRWTeif0gQDGu04MXW05PKDM4irOnhAzQahVz9+/qHs3fWr8F7FoaPEkhBzoEmGsLk64uVLyiw0QDe9iB0D5RoMTvDVxNS4XBxVBesp0QU3QQlFkChlTluVoMEGq1tUloZilW0+2pHnJRrmlaZv+5Mw9ZJnw8hdKy2q21LVtYYKmBW4wwunj+mWSdjwjQkOv1g4MdE+HbDp1+jD53GGZXzU5Cj9CCiFaAAiLg9T481PokZcKfGHSxi/x1K0s8Uiyjssigtix1uS0K3nHqiuPPcAalpRUTiH+sQfBw8OU2UAlk3a+tk4NyJWe3amelkXVXnnzbS8oVTYOn4wSPpMlpI6EF9h/EjPSp4J8JduTa8YoS8nBie3fpm9iqiHzV0F/MNBdbpDrLy15ExiO7DnRZMEcj7HtEm/3yI7Z1fvN24IGFOV+KcJIyoMTzk/D6TEJ5vUTdPnpacx37hrFEGTxxb8HC10/D9nen6UhfwM=
  file: vanadia-$TRAVIS_TAG.${TRAVIS_OS_NAME/osx/darwin}-amd64.tar.gz
  skip_cleanup: true
  on:
    repo: bukalapak/vanadia
    tags: true
